name: CD

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: actions/core@1.10.0

    - name: Set Short github sha
      id: short-sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
